### ISSUE TITLE
faillure on yum install libXtst.i686 "Multilib version problems found"

### ISSUE THREAD

**Issue by pgleghorn** [biemond/biemond-wls-vagrant-oim#2]
==> oimdb: Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install libXtst.i686' returned 1: Error:  Multilib version problems found. This often means that the r                            oot
==> oimdb:        cause is something else and multilib version checking is just
==> oimdb:        pointing out that there is a problem. Eg.:
==> oimdb:
==> oimdb:          1. You have an upgrade for libXtst which is missing some
==> oimdb:             dependency that another package requires. Yum is trying to
==> oimdb:             solve this by installing an older version of libXtst of the
==> oimdb:             different architecture. If you exclude the bad architecture
==> oimdb:             yum will tell you what the root cause is (which package
==> oimdb:             requires what). You can try redoing the upgrade with
==> oimdb:             --exclude libXtst.otherarch ... this should give you an error
==> oimdb:             message showing the root cause of the problem.
==> oimdb:
==> oimdb:          2. You have multiple architectures of libXtst installed, but
==> oimdb:             yum can only see an upgrade for one of those arcitectures.
==> oimdb:             If you don't want/need both architectures anymore then you
==> oimdb:             can remove the one with the missing update and everything
==> oimdb:             will work.
==> oimdb:
==> oimdb:          3. You have duplicate versions of libXtst installed already.
==> oimdb:             You can use "yum check" to get yum show these errors.
==> oimdb:
==> oimdb:        ...you can also use --setopt=protected_multilib=false to remove
==> oimdb:        this checking, however this is almost never the correct thing to
==> oimdb:        do as something else is very likely to go wrong (often causing
==> oimdb:        much more problems).
==> oimdb:
==> oimdb:        Protected multilib versions: libXtst-1.2.2-2.1.el6.i686 != libXtst-1.2.1-2.el6.x86_64
==> oimdb:  You could try using --skip-broken to work around the problem
==> oimdb:  You could try running: rpm -Va --nofiles --nodigest

**Comment by biemond** [comment]
Hi 

yeah Centos changed their yum packages but can you use this one instead
https://github.com/biemond/biemond-orawls-vagrant-oim_oam

the wls vagrant boxes aren't maintained anymore and replaced by the orawls ones.

Thanks
